# Generated by Django 3.0.6 on 2020-05-17 10:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Describe this order in a few short words.', max_length=255, null=True)),
                ('address', models.CharField(blank=True, help_text='Address of where this request should be delivered.', max_length=255, null=True)),
                ('order_body', models.TextField(help_text='Enter your order here.', null=True, verbose_name='Order')),
                ('creation_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(blank=True, default='PENDING', max_length=255, null=True)),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_from', to=settings.AUTH_USER_MODEL)),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
