# Generated by Django 3.0.6 on 2020-05-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='order_body',
            field=models.TextField(help_text='Enter your order here.', null=True),
        ),
    ]
