# Generated by Django 3.0.6 on 2020-05-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_orderrequest_order_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='address',
            field=models.CharField(blank=True, help_text='Address of where this request should be delivered.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='title',
            field=models.CharField(help_text='Describe this order in a few short words.', max_length=255, null=True),
        ),
    ]
