# Generated by Django 3.0.6 on 2020-05-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20200516_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='order_body',
            field=models.TextField(help_text='Enter your order here.', null=True, verbose_name='Order'),
        ),
    ]
