# Generated by Django 3.0.6 on 2020-05-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_remove_orderrequest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(blank=True, default='STARTED', max_length=255, null=True),
        ),
    ]
